version: '3.9'

services:
  narco-admin-panel:
    image: narco-admin-panel:latest
    container_name: narco-admin-panel
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/usr/src/app
    restart: unless-stopped
    ports:
      - '4567:4567'
    networks:
      - narco-network
    environment:
      VITE_URL: ${VITE_URL}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_BASE_URL: ${VITE_BASE_URL}

networks:
  narco-network:
    external: true
