version: '3.9'

services:
  narco-admin-panel:
    image: narco-admin-panel:latest
    container_name: narco-admin-panel
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4567:4567'
    networks:
      - narco-network
    environment:
      ANGULAR_URL: ${ANGULAR_URL}
      ANGULAR_API_BASE_URL: ${ANGULAR_API_BASE_URL}
      ANGULAR_BASE_URL: ${ANGULAR_BASE_URL}
      ANGULAR_CRYPTO_KEY: ${ANGULAR_CRYPTO_KEY}

networks:
  narco-network:
    external: true
